package com.vehiclemanagement.domain;

import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;
import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.OffsetDateTime;

/**
 * One truck, with exactly one live owner and no ownership history.
 *
 * <p><b>Why ownership is two columns here and not two link tables.</b> "Exactly one owner, a
 * company or a person, never both" is a single-row invariant, and only a single-row CHECK can
 * enforce it. Split across {@code vehicle_x_company} and {@code vehicle_x_user}, two concurrent
 * transfers under READ COMMITTED each read the other's table before it commits, see nothing,
 * and both succeed — leaving two owners with no constraint violated. Here they contend on this
 * row's lock instead, and no service code has to remember to take it.
 *
 * <p>{@code vehicle_x_company} still exists as a read-only view over this table, so queries
 * written against that name work. Inserting into it fails, which is correct.
 *
 * <p>An OWNER row in {@code vehicle_x_user} is bound to {@link #ownerUserId} by a composite
 * foreign key, so the two can never disagree; see VehicleUser.
 */
@Entity
@Table(name = "vehicles")
public class Vehicle {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Canonical spelling only — upper-case, no separators. See Normalizer.registration.
     * Null when the plate is not known yet (changeset 023).
     */
    @Column(name = "registration_number", length = 12, unique = true)
    private String registrationNumber;

    /** Null when the body type is not known yet (changeset 023). */
    @Column(name = "body_type_id")
    private Long bodyTypeId;

    @Column(name = "no_of_axles")
    private Short noOfAxles;

    @Column(name = "no_of_wheels")
    private Short noOfWheels;

    /** Free text by decision: "20 Ton", "50 Ton". No enum, no master. */
    @Column(length = 32)
    private String capacity;

    /**
     * Derived by the database from {@link #capacity}, for sorting and range filters only.
     *
     * <p>Read-only here on purpose: a field the application maintains can contradict the text it
     * came from, and this codebase prefers native UPDATEs — exactly the writer that would forget
     * to keep the two in step.
     *
     * <p>{@code @Generated} is what makes Hibernate read it back after every write. Without it
     * the column is correct in the database and <b>stale in the object</b>, so the response to a
     * PUT reports the tonnage the vehicle had before the edit — a wrong number, returned
     * confidently, by the very request that changed it.
     */
    @Generated(event = {EventType.INSERT, EventType.UPDATE})
    @Column(name = "capacity_tons", insertable = false, updatable = false)
    private BigDecimal capacityTons;

    @Column(name = "length_ft")
    private BigDecimal lengthFt;

    @Column(name = "owner_company_id")
    private Long ownerCompanyId;

    @Column(name = "owner_user_id")
    private Long ownerUserId;

    /**
     * Read-only discriminator, generated by the database. Exists so vehicle_x_location can carry
     * a composite FK that makes a preferred location on a company-owned vehicle a referential
     * impossibility rather than a rule someone has to remember.
     */
    @Generated(event = {EventType.INSERT, EventType.UPDATE})
    @Column(name = "is_company_owned", insertable = false, updatable = false)
    private Boolean companyOwned;

    @Column(name = "is_active", nullable = false)
    private boolean active = true;

    @Column(length = 2000)
    private String notes;

    @Generated(event = EventType.INSERT)
    @Column(name = "created_at", insertable = false, updatable = false)
    private OffsetDateTime createdAt;

    @Generated(event = {EventType.INSERT, EventType.UPDATE})
    @Column(name = "updated_at", insertable = false, updatable = false)
    private OffsetDateTime updatedAt;

    protected Vehicle() {
    }

    public Vehicle(String registrationNumber, Long bodyTypeId) {
        this.registrationNumber = registrationNumber;
        this.bodyTypeId = bodyTypeId;
    }

    public Long getId() { return id; }
    public String getRegistrationNumber() { return registrationNumber; }
    public void setRegistrationNumber(String v) { this.registrationNumber = v; }
    public Long getBodyTypeId() { return bodyTypeId; }
    public void setBodyTypeId(Long v) { this.bodyTypeId = v; }
    public Short getNoOfAxles() { return noOfAxles; }
    public void setNoOfAxles(Short v) { this.noOfAxles = v; }
    public Short getNoOfWheels() { return noOfWheels; }
    public void setNoOfWheels(Short v) { this.noOfWheels = v; }
    public String getCapacity() { return capacity; }
    public void setCapacity(String v) { this.capacity = v; }
    public BigDecimal getCapacityTons() { return capacityTons; }
    public BigDecimal getLengthFt() { return lengthFt; }
    public void setLengthFt(BigDecimal v) { this.lengthFt = v; }
    public Long getOwnerCompanyId() { return ownerCompanyId; }
    public Long getOwnerUserId() { return ownerUserId; }
    public boolean isCompanyOwned() { return Boolean.TRUE.equals(companyOwned); }
    public boolean isActive() { return active; }
    public void setActive(boolean active) { this.active = active; }
    public String getNotes() { return notes; }
    public void setNotes(String notes) { this.notes = notes; }
    public OffsetDateTime getCreatedAt() { return createdAt; }
    public OffsetDateTime getUpdatedAt() { return updatedAt; }

    /**
     * Sets both owner columns at once, because they are one fact.
     *
     * <p><b>Call this only from VehicleService.setOwner.</b> An ownership change also has to
     * retire the old OWNER row in vehicle_x_user and, when a company takes over, the vehicle's
     * own preferred locations — in that order, before this runs. Calling it directly trips
     * fk_vxu_owner_matches or fk_vxl_vehicle, which is the database refusing to let the change
     * be half-done rather than a bug.
     */
    public void assignOwner(Long companyId, Long userId) {
        this.ownerCompanyId = companyId;
        this.ownerUserId = userId;
    }
}
